name: Registry
description: Validate token and generate certificate
inputs:
  labels:
    description: Kubernetes cluster label selector
    required: false
runs:
  using: docker
  image: "docker://reg-hk.agodadev.io/actions/kubectl:1.18.0"
  entrypoint: /registry.sh
  env: 
    option_selector: ${{ inputs.labels }}
