name: Registry
description: Validate token and generate certificate
inputs:
  labels:
    description: Kubernetes cluster label selector
    required: false
runs:
  using: docker
  image: 'docker://fergusn/kubectl'
  entrypoint: sh
  args:
  - -c
  - |
    env && ls -a GITHUB_WORKSPACE && echo "::set-output name=matrix::'$(kubectl get clusters $(if [ ! -z $labels ]; then echo "-l"; fi) $(echo $labels | paste -sd "," -) -o json | jq -c "{include: [{cluster: .items[].metadata.name}]}")'"
