name: Rollout
description: Schedule the rollout of one or more repositories and clusters
inputs:
  clusters:
    description: Kubernetes clusters names
    required: false
  selector:
    description: Kubernetes clusters labels selector
    required: false
  repositories:
    description: GitHub repositories
    required: false
  ref:
    description: Git branch or sha
    required: false
runs:
  using: docker
  image: "docker://reg-hk.agodadev.io/actions/rollout:latest"
