name: Deploy
description: Deploy kubernetes manifests
inputs:
  namespace:
    description: Kubernetes namespace
    required: true
    default: default
  namespace:
    description: Filename
    required: true
runs:
  using: docker
  image: 'docker://fergusn/deploy'
  args:
  - -n 
  - ${{ inputs.namespace }}
  - -f 
  - ${{ inputs.filename }}  