name: Authenticate
description: Validate token and generate certificate
inputs:
  cluster:
    description: Kubernetes cluster name
    required: true
  namespace:
    description: Default namespace
    required: false
runs:
  using: docker
  image: "docker://reg-hk.agodadev.io/kubernetes/action-authenticate:v1"
  post-entrypoint: "/post-entrypoint.sh"
  args:
  - ${{ github.token }}
  - ${{ inputs.cluster }}
  - ${{ inputs.namespace }}