name: Authenticate
description: Validate token and generate certificate
inputs:
  cluster:
    description: Kubernetes cluster name
    required: true
  token:
    description: GitHub Token
    required: true
  server:
    description: GitHub Server
    required: true
  repo:
    description: GitHub Repo
    required: true
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        env && mkdir -p $HOME/.kube && curl -H "Authorization: Bearer ${{ inputs.token }}" http://authenticate/$(INPUT_SERVER:8)/$INPUT_REPO?cluster=$INPUT_CLUSTER > $HOME/.kube/config
      
