name: Authenticate
description: Validate token and generate certificate
inputs:
  token:
    description: GitHub Token
    required: true
  cluster:
    description: Kubernetes cluster name
    required: true
  namespace:
    description: Default namespace
    required: false
runs:
  using: docker
  image: "docker://reg-hk.agodadev.io/actions/authenticate:latest"
  post-entrypoint: '/cleanup.sh'
  args:
  - ${{ inputs.token }}
  - ${{ inputs.cluster }}
  - ${{ inputs.namespace }}
