name: Authenticate
description: Validate token and generate certificate
inputs:
  token:
    description: GitHub Token
    required: true
  namespace:
    description: Cluster namespace
    required: false
    default: default
  cluster:
    description: Cluster name
    required: true
runs:
  using: docker
  image: "docker://reg-hk.agodadev.io/actions/authenticate:latest"
  post-entrypoint: '/usr/local/bin/cleanup.sh'
