name: Authenticate
description: Validate token and generate certificate
inputs:
  cluster:
    description: Kubernetes cluster name
    required: true
  token:
    description: GitHub Token
    required: true
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        mkdir -p $HOME/.kube && curl -H "Authorization: Bearer ${{ inputs.token }}" http://authenticate/$(GITHUB_SERVER_URL:8)/$GITHUB_REPOSITORY?cluster=${{ inputs.cluster }} > $HOME/.kube/config
      
