name: Authenticate
description: Validate token and generate certificate
inputs:
  cluster:
    description: Kubernetes cluster name
    required: true
  token:
    description: GitHub Token
    required: true
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        echo "::set-env name=KUBECONFIG::$GITHUB_WORKSPACE/.kube/config" && mkdir -p $GITHUB_WORKSPACE/.kube && curl -q -H "Authorization: Bearer ${{ inputs.token }}" http://authenticate/${GITHUB_SERVER_URL:8}/$GITHUB_REPOSITORY?cluster=${{ inputs.cluster }} > $GITHUB_WORKSPACE/.kube/config; echo $GITHUB_WORKSPACE;
      
